language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
  - rustdoc --test README.md -L target
  - cargo doc
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = nightly ] &&
  echo '<meta http-equiv=refresh content=0;url=splay/index.html>' > target/doc/index.html &&
  pip install ghp-import --user $USER &&
  $HOME/.local/bin/ghp-import -n target/doc &&
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    - secure: poQ3qeZzKOTQyEBIC8X4SVAToN/zV0QAxeYqUpjRbT1HNlKsTVuHiQmbeAuYdiKEh6fkx6VsKG6DekrrYsK4/HzpRWFHxp8sLZtmTv+rBTlOQOMno+wS5YpNsm3v3n1nD9tGBMDDLCGOsFsMRGKtdJzyXqlIlnMJbKs+Ud6DBBw=
    - secure: SaRBNK8Wryx9zOET88L79HK/gZX7MC3h4KFeWbe2hXJP2TnXe58WYSp1Cy/PU+buQjVzxzMucZnRdkyrq2UOM3ruSljpKA11ySNYsRT4ppdnTiqyU9cnv3H2c0SfFoezGE8gGjRXGBce+4KF1waJ3ybkPekyxZrCC6gR4SZSots=
notifications:
  email:
    on_success: never
