language: rust
script:
- cargo build
- cargo test
- cargo doc
after_success: ! '[ $TRAVIS_BRANCH = master ] && [ $TRAVIS_PULL_REQUEST = false ]
  && echo ''<meta http-equiv=refresh content=0;url=splay/index.html>'' > target/doc/index.html
  && sudo pip install ghp-import && ghp-import -n target/doc && git push -fq https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  gh-pages '
env:
  global:
  - secure: MfyWyViyqw8kU5AwCWprXpiMK5Gq+aqVQuYRwe016kOPqEJpfnb+ILJ4T59/Le9DUVEpMn1HIJ6FX8P7XKAcG4EMZNBWNAubRzYByaM3/iqOWJfhBPLQgAg6SMZSfAdiN1cX8IGbVKdLyso5GEKFDD3lfaRZxtyO+CKAWbW6zZc=
